FROM tensorflow/tensorflow
 
RUN pip install boto3
RUN pip install mlflow
RUN pip install tensorflow
RUN pip install tensorflow_datasets
RUN pip install tensorflow_addons
RUN pip install pandas
RUN pip install numpy
RUN pip install pillow

RUN pip install --force-reinstall --no-cache-dir http://vmi504080.contaboserver.net:9876/packages/clientlib/infinstor-2.0.44-py3-none-any.whl
