FROM tensorflow/tensorflow
 
RUN pip install boto3
RUN pip install mlflow
RUN pip install tensorflow
RUN pip install tensorflow_datasets
RUN pip install tensorflow_addons
RUN pip install pandas
RUN pip install numpy
