FROM tensorflow/tensorflow
 
RUN pip install boto3
RUN pip install mlflow
RUN pip install tensorflow
RUN pip install tensorflow_datasets
RUN pip install pandas
RUN pip install numpy

RUN pip install http://vmi504080.contaboserver.net:9876/packages/parallels-plugin/parallels_plugin-0.3.6-py3-none-any.whl
